### ISSUE TITLE
Working with large data and multilineString

### ISSUE THREAD

**Issue by trandinh135** [HichamZouarhi/offline-routing-OL3#1]
I replace your data by my geojson(~6mb/4000Features), in my data coordinates is stored in MultiLineString type. It not work well anymore. How can i fix it

**Comment by hichamzouarhi** [comment]
Hi tardinh135, thanks for using this tool.
It uses Linestring geometries, I'm full on my hands lately to make changes to it.
First you can convert it to Linestrings using QGIS or PostGIS.
To make this algorithm go faster, you can create your Network while your HTML page loads, meaning this line
    `var network = createNetwork(yourFeatureCollection);`
should go somewhere in the beginning of your code
Then you can call later the `getShortestPath` function

**Comment by trandinh135** [comment]
What about 'source' and 'target' properties in Feature? Must i have those?    My data have no property like that

**Comment by trandinh135** [comment]
[SimpleLineString.geojson.txt](https://github.com/HichamZouarhi/offline-routing-OL3/files/610386/SimpleLineString.geojson.txt)
Please test with my data, I converted to LineString, but it not working

**Comment by hichamzouarhi** [comment]
For source and target you have to put the coordinates of your start an end points in [longitude, latitude] ( as an answer to apparently a deleted comment )

**Comment by trandinh135** [comment]
Thanks , I resolved

**Comment by F3L1X79** [comment]
HichamZouarhi, many thanks for the code! Helped me a lot!

@trandinh135 I got exactly the same problem! Mind if your share some code for making it working with MultiLineString?

**Comment by F3L1X79** [comment]
This is what I ended up and it worked fine !

```
var lineStrings = [];
multiLineFeatures.forEach(function (mlf) {
    var points = mlf.getGeometry().getCoordinates();
    for (var i = 0; i < points.length; i++) {
        for (var j = 0; j < points[i].length - 1; j++) {
            var start = points[i][j];
            var end = points[i][j + 1];
            var lineString = new ol.Feature({
                geometry: new ol.geom.LineString([start, end])
            });
            lineStrings.push(lineString);
        }
    }
});
```

**Comment by F3L1X79** [comment]
Plus you should credit this imo: https://github.com/andrewhayward/dijkstra

**Comment by hichamzouarhi** [comment]
@F3L1X79 Thanks, I updated it :)

**Comment by trandinh135** [comment]
@F3L1X79 follow @HichamZouarhi 's approach .You have to manually convert MultiLineString to LineString.
I used QGIS
